source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/LexoVideo/lexo-dev-specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, '15.0'

target 'TTPlayerDecryptDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit'
  
  # Pods for TTPlayerDecryptDemo
  pod 'DRMLib', '2.1.1'
  
  ## TT
  pod 'TTSDK', '1.41.3.603-premium', :subspecs => ['Player']
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # disable bit code
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        # disable arm64 on simulator
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
        File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
      end
    end
    
  end
end
